build:
	cd Q1 && javac -classpath /usr/share/tomcat9/lib/servlet-api.jar -d WEB-INF/classes InputServlet.java ResultServlet.java

copy:
	cp -r Q1 /usr/share/tomcat9/webapps/Q1
	cp -r Q2 /usr/share/tomcat9/webapps/Q2